//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublishITService
{
    using System;
    using System.Collections.Generic;
    
    public partial class media
    {
        public media()
        {
            this.document = new HashSet<document>();
            this.rating = new HashSet<rating>();
            this.rent = new HashSet<rent>();
            this.genre = new HashSet<genre>();
        }
    
        public int media_id { get; set; }
        public int user_id { get; set; }
        public int format_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string location { get; set; }
        public Nullable<double> average_rating { get; set; }
        public Nullable<int> number_of_downloads { get; set; }
    
        public virtual ICollection<document> document { get; set; }
        public virtual format format { get; set; }
        public virtual user user { get; set; }
        public virtual ICollection<rating> rating { get; set; }
        public virtual ICollection<rent> rent { get; set; }
        public virtual video video { get; set; }
        public virtual ICollection<genre> genre { get; set; }
    }
}
