//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublishITService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RentIt09Entities : DbContext
    {
        public RentIt09Entities()
            : base("name=RentIt09Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<document> document { get; set; }
        public DbSet<format> format { get; set; }
        public DbSet<genre> genre { get; set; }
        public DbSet<media> media { get; set; }
        public DbSet<NAMES> NAMES { get; set; }
        public DbSet<organization> organization { get; set; }
        public DbSet<person> person { get; set; }
        public DbSet<profession> profession { get; set; }
        public DbSet<rating> rating { get; set; }
        public DbSet<rent> rent { get; set; }
        public DbSet<role> role { get; set; }
        public DbSet<user> user { get; set; }
        public DbSet<video> video { get; set; }
    }
}
