//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublishITService
{
    using System;
    using System.Collections.Generic;
    
    public partial class profession
    {
        public profession()
        {
            this.person = new HashSet<person>();
        }
    
        public int profession_id { get; set; }
        public string profession1 { get; set; }
    
        public virtual ICollection<person> person { get; set; }
    }
}
