//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublishITService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RentIt09Entities : DbContext, IPublishITEntities
    {
        public RentIt09Entities()
            : base("name=RentIt09Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }


        public IDbSet<document> document { get; set; }
        public IDbSet<format> format { get; set; }
        public IDbSet<genre> genre { get; set; }
        public IDbSet<media> media { get; set; }
        public IDbSet<organization> organization { get; set; }
        public IDbSet<person> person { get; set; }
        public IDbSet<profession> profession { get; set; }
        public IDbSet<rating> rating { get; set; }
        public IDbSet<rent> rent { get; set; }
        public IDbSet<role> role { get; set; }
        public IDbSet<user> user { get; set; }
        public IDbSet<video> video { get; set; }
    }
}
