//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublishITService
{
    using System;
    using System.Collections.Generic;
    
    public partial class role
    {
        public role()
        {
            this.user = new HashSet<user>();
            this.user1 = new HashSet<user>();
        }
    
        public int role_id { get; set; }
        public string role1 { get; set; }
    
        public virtual ICollection<user> user { get; set; }
        public virtual ICollection<user> user1 { get; set; }
    }
}
