//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublishITService
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.media = new HashSet<media>();
            this.rating = new HashSet<rating>();
            this.rent = new HashSet<rent>();
            this.role = new HashSet<role>();
        }
    
        public int user_id { get; set; }
        public int organization_id { get; set; }
        public string name { get; set; }
        public string user_name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string salt { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<media> media { get; set; }
        public virtual organization organization { get; set; }
        public virtual ICollection<rating> rating { get; set; }
        public virtual ICollection<rent> rent { get; set; }
        public virtual ICollection<role> role { get; set; }
    }
}
