//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublishITService
{
    using System;
    using System.Collections.Generic;
    
    public partial class video
    {
        public int media_id { get; set; }
        public Nullable<double> length { get; set; }
        public Nullable<int> number_of_rents { get; set; }
        public Nullable<int> number_of_trailer_views { get; set; }
    
        public virtual media media { get; set; }
    }
}
